### ISSUE TITLE
Question: Does the type generation work for custom scalars?

### ISSUE THREAD

**Issue by capaj** [helios1138/graphql-typed-client#1]
We use a lot of custom scalars from https://github.com/capaj/graphql-scalars, would the type def generation work even for those?

**Comment by helios1138** [comment]
custom scalar types are generated as aliases to `any` (since we can't know anything about them)
```ts
export type DateTime = any
```
and then these types are used as field types, so you'll still have readable type names in code completion

![](https://i.gyazo.com/b1b31b6e6e171a5a4ff2395cccfb8840.png)

**Comment by capaj** [comment]
thanks. It would be nice to be able to define a custom scalar and be able to define how it should deserialize. Like for example if I had DateTime, I could define it to deserialize into a moment instance instead of just being a string.

**Comment by helios1138** [comment]
@capaj good idea, I will put it on the roadmap!

**Comment by capaj** [comment]
I'll create that as a separate issue.
