### ISSUE TITLE
Cli process always is finished with 0 code

### ISSUE THREAD

**Issue by p-fedyukovich** [helios1138/graphql-typed-client#16]
Hi!
I faced with CI problem when error is occurred program exits with 0 code, which means that everything is okay. So that afterwards processes proceeds. I think that is wrong behavior, better close application with 1 code
https://github.com/helios1138/graphql-typed-client/blob/ee79c4a006ae390b15539afc4897edd846984f23/src/cli.ts#L40

**Comment by helios1138** [comment]
fixed in https://github.com/helios1138/graphql-typed-client/commit/e2811c46bf5777004da64f031ab351e16412bde4
