### ISSUE TITLE
Suggestion: Generate client from TypeGraphql models

### ISSUE THREAD

**Issue by ozyman42** [helios1138/graphql-typed-client#23]
TypeGraphql models could be shared between client and server, this library could use the model files to generate a typed client without the need of a running server.

**Comment by helios1138** [comment]
Not sure I understand. Technically this library does not need running a server, only that you have a schema available somehow and a way to execute it

**Comment by helios1138** [comment]
@AlexLeung Not sure I understand. Technically this library does not need running a server, only that you have a schema available somehow and a way to execute it

**Comment by ozyman42** [comment]
Nevermind. I didn't notice that there was a `-s` option.
