### ISSUE TITLE
Question/FR: How to get graphql query string?

### ISSUE THREAD

**Issue by sido420** [helios1138/graphql-typed-client#28]
First of all thanks for `graphql-typed-client`. 

I want to use a specific feature thats to convert from JS query/mutation object to GQL string.

I skimmed through the documentation, but did not find anything that would allow me to do just that. 

I am specifically looking for.
```
myClient.query({
  user: [{ id: 'USER_ID' }, {
      username: 1,
      email: 1,
      on_AdminUser: {
        isSuperAdmin: 1,
      },
  }],
}).generateGQL()
```
I have my own client that I'd like to use to send queries to server.

**Comment by helios1138** [comment]
@sido420 currently the library is completely agnostic as to how you make queries to the server.  When instantiating a client, you provide it with a fetcher function that does the querying and his function can be implemented however you want, so if you want to use your own client - you can do it.

```js
export const myClient = createClient({
  fetcher: ({ query, variables }) => {
    // YOUR CLIENT CALL HERE,
  },
})
```

As to the JS-to-Graphql conversion, there currently isn't a single exported function that does that.

**Comment by sido420** [comment]
Thanks. I will try to figure out something.
