### ISSUE TITLE
Feature request: request batching

### ISSUE THREAD

**Issue by capaj** [helios1138/graphql-typed-client#3]
would be nice if this library had support for query batching.

We currently use apollo-client and it's query batching strategy is to wait with any query fox X ms and if there are any consecutive it just adds them into array and dispatches the array to the server I think. So it should be trivial.

**Comment by helios1138** [comment]
https://github.com/helios1138/graphql-typed-client/tree/next will have the ability to pass custom fetcher function, which can be implemented in any way one would like, including using `apollo-client`
