### ISSUE TITLE
replace ws with isomorphic-ws for subscription in browser

### ISSUE THREAD

**Issue by michelepra** [helios1138/graphql-typed-client#33]
When build for browser ws module must not be taken

https://github.com/helios1138/graphql-typed-client/blob/0bdd5736fc071ae09131852038216738bceb7215/package.json#L72

`"isomorphic-ws": "^4.0.1"`

https://github.com/helios1138/graphql-typed-client/blob/0bdd5736fc071ae09131852038216738bceb7215/src/client/getSubscriptionCreator.ts#L4

`import ws from "isomorphic-ws";`

**Comment by michelepra** [comment]
no chance

**Comment by IceBlizz6** [comment]
@michelepra 
The maintainer is probably gone.
But the issue is still relevant, and thanks to you we got an easy fix on our local fork.
So for whatever it's worth... thanks!
